CREATE DATABASE  ControlIncidenciasDB
GO
USE ControlIncidenciasDB
GO

CREATE TABLE EDIFICIO(
	 ID INT IDENTITY,
	 Nombre NVARCHAR(20) NOT NULL, 
	 Ubicacion NVARCHAR(100) NOT NULL,
	 ID_Depto INT
)
GO
CREATE TABLE LOCALIZACION( 
	 ID INT IDENTITY,
	 Nombre NVARCHAR(25) NOT NULL,
	 NumPlanta INT,
	 ID_Edificio INT,
	 Ubicacion NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE DEPARTAMENTO(
	ID INT IDENTITY,
	Nombre NVARCHAR(20) NOT NULL,
	ID_EmpEncar INT
)
GO
CREATE TABLE EMPLEADO(
	ID INT IDENTITY,
	Nombre NVARCHAR(40) NOT NULL,
	Email NVARCHAR(35) NOT NULL,
	Celular NVARCHAR(12) NOT NULL,
	Direccion NVARCHAR(30) NOT NULL,
	ID_Rol INT
)
GO
CREATE TABLE EMPLEADO_DEPTO(
	ID_Empleado INT,
	ID_Depto INT
)
GO
CREATE TABLE ROL(
	ID INT IDENTITY,
	Nombre NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE PROVEEDOR(
	ID INT IDENTITY,
	Nombre NVARCHAR(20) NOT NULL,
	RFC NVARCHAR(13) NOT NULL,
	Email NVARCHAR(20) NOT NULL,
	Telefono NVARCHAR(12) NOT NULL,
	Direccion NVARCHAR(40) NOT NULL
)
GO
CREATE TABLE CI(
	ID INT IDENTITY,
	Nombre NVARCHAR(20) NOT NULL,
	Descripcion NVARCHAR(40) NOT NULL,
	NumSerie NVARCHAR(30) NOT NULL,
	FechaAdquisicion DATE NOT NULL,
	ID_Localizacion INT,
	ID_Encargado INT,
	ID_Proveedor INT
)
GO
CREATE TABLE INCIDENCIA(
	ID INT IDENTITY,
	Descripcion NVARCHAR(50) NOT NULL,
	FechaInicio DATE,
	FechaTerminacion DATE,
	ID_Prioridad INT,
	ID_CI INT,
	ID_Tecnico INT,
	ID_Stat INT
)
GO
CREATE TABLE PRIORIDAD(
	ID INT IDENTITY,
	Descripcion NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE ESTATUS_INCIDENCIA(
	ID INT IDENTITY,
	Descripcion NVARCHAR(15) NOT NULL
)
GO

---------------------------------------- PRIMARY KEYS ----------------------------------------

ALTER TABLE EDIFICIO
ADD CONSTRAINT PK_Edificio PRIMARY KEY(ID)

ALTER TABLE LOCALIZACION
ADD CONSTRAINT PK_Localizacion PRIMARY KEY(ID)

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PK_Departamento PRIMARY KEY(ID)

ALTER TABLE EMPLEADO
ADD CONSTRAINT PK_Empleado PRIMARY KEY(ID)

ALTER TABLE ROL
ADD CONSTRAINT PK_Rol PRIMARY KEY(ID)

ALTER TABLE PROVEEDOR
ADD CONSTRAINT PK_Proveedor PRIMARY KEY(ID)

ALTER TABLE CI
ADD CONSTRAINT PK_CI PRIMARY KEY(ID)

ALTER TABLE ESTATUS_INCIDENCIA
ADD CONSTRAINT PK_EstatusIncidencia PRIMARY KEY(ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT PK_Incidencia PRIMARY KEY(ID)
GO

---------------------------------------- FOREIGN KEYS ----------------------------------------

ALTER TABLE EDIFICIO
ADD CONSTRAINT FK_Edificio_Depto FOREIGN KEY(ID_Depto) REFERENCES DEPARTAMENTO (ID)

ALTER TABLE LOCALIZACION
ADD CONSTRAINT FK_Localizacion_Edificio FOREIGN KEY(ID_Edificio) REFERENCES EDIFICIO (ID)

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_Encargado_Depto FOREIGN KEY(ID_EmpEncar) REFERENCES EMPLEADO (ID)

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_Empleado_Rol FOREIGN KEY(ID_Rol) REFERENCES ROL (ID)

ALTER TABLE EMPLEADO_DEPTO
ADD CONSTRAINT FK_EmpleadoDepto_Empleado FOREIGN KEY(ID_Empleado) REFERENCES EMPLEADO (ID)

ALTER TABLE EMPLEADO_DEPTO
ADD CONSTRAINT FK_EmpleadoDepto_Depto FOREIGN KEY(ID_Depto) REFERENCES DEPARTAMENTO (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Localizacion FOREIGN KEY(ID_Localizacion) REFERENCES LOCALIZACION (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Encargado FOREIGN KEY(ID_Encargado) REFERENCES EMPLEADO (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Provedor FOREIGN KEY(ID_Proveedor) REFERENCES PROVEEDOR (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Indcidencia_CI FOREIGN KEY(ID_CI) REFERENCES CI (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Indcidencia_Tecnico FOREIGN KEY(ID_Tecnico) REFERENCES EMPLEADO (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Incidencia_Estatus FOREIGN KEY(ID_Stat) REFERENCES ESTATUS_INCIDENCIA (ID)
GO

---------------------------------------- POBLACION ----------------------------------------
INSERT INTO ROL(Nombre) 
VALUES ('ADMINISTRADOR') 
INSERT INTO ROL (Nombre) 
VALUES ('JEFE DE TALLER') 
INSERT INTO ROL (Nombre) 
VALUES ('TECNICO') 
INSERT INTO ROL (Nombre) 
VALUES ('DOCENTE') 
SELECT * FROM ROL

INSERT INTO PRIORIDAD(Descripcion)
VALUES('ALTA')
INSERT INTO PRIORIDAD(Descripcion)
VALUES('MEDIA')
INSERT INTO PRIORIDAD(Descripcion)
VALUES('BAJA')
SELECT * FROM PRIORIDAD

INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('RESUELTA')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('PENDIENTE')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('EN PROCESO')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('RECHAZADA')
SELECT * FROM ESTATUS_INCIDENCIA

INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol)
VALUES('MARCO ANTONIO RODRIGUEZ AVILES','Marco@itculiacan.edu.mx','6671234567','Villa Alegria',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol)
VALUES('JORGE GUILLERMO MOYA PALAZUELOS','Jorge@itculiacan.edu.mx','6672567032','Los Cascaveles',2)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol)
VALUES('NOEL GARCIA INZUNZA','Noel@itculiacan.edu.mx','6670987654','Rancho Contento',3)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol)
VALUES('ELIZABETH BARRAZA GARCIA','Elizabeth@itculiacan.edu.mx','6610293845','Los Pinos',4)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol)
VALUES('MARIA DEL ROSARIO GONZALEZ ALVAREZ','Rosario@itculiacan.edu.mx','6610200826','Las lomas',4)
SELECT * FROM EMPLEADO

SELECT E.Nombre,E.Email,E.Celular,E.Direccion,R.Nombre [Rol],ND.Nombre [Departamento] FROM EMPLEADO E 
INNER JOIN EMPLEADO_DEPTO D ON E.ID = D.ID_Empleado
INNER JOIN DEPARTAMENTO ND ON D.ID_Depto = ND.ID
INNER JOIN ROL R ON E.ID_Rol = R.ID
WHERE E.ID = 1

SELECT R.Nombre FROM EMPLEADO E INNER JOIN ROL R ON E.ID_Rol = R.ID WHERE E.ID = 1

SELECT ND.Nombre FROM EMPLEADO E INNER JOIN EMPLEADO_DEPTO D ON E.ID = D.ID_Empleado INNER JOIN DEPARTAMENTO ND ON D.ID_Depto = ND.ID WHERE E.ID = 1

--UPDATE EMPLEADO SET Celular='NOEL GARCIA INZUNZA' WHERE ID=3
--UPDATE EMPLEADO SET Direccion='NOEL GARCIA INZUNZA' WHERE ID=3

SELECT ID FROM EMPLEADO WHERE Email LIKE 'noel@itculiacan.edu.mx'


INSERT INTO DEPARTAMENTO(Nombre,ID_EmpEncar)
VALUES('SISTEMAS',5)
SELECT * FROM DEPARTAMENTO

INSERT INTO EDIFICIO(Nombre,Ubicacion,ID_Depto)
VALUES('A','CERCA DE LA ENTRADA PRINCIPAL AUN LADO DEL ESTANQUE',1)
SELECT * FROM EDIFICIO

INSERT INTO LOCALIZACION(Nombre,NumPlanta,ID_Edificio,Ubicacion)
VALUES('CUBICULO 4',1,1,'DENTRO DEL EDIFICIO GIRAR A LA IZQUIERDA Y CAMINAR HASTA EL FONDO')
SELECT * FROM LOCALIZACION

INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(1,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(2,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(3,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(4,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(5,1)
SELECT * FROM EMPLEADO_DEPTO
